<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lixiaoyan" ignored="1" tests="2" failures="1" timestamp="21 五月 2018 09:04:03 GMT" time="3.063" errors="0">
  <testcase name="testCase2" time="3.03" classname="OtherTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method OtherTest.testCase2() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method OtherTest.testCase2() didn't finish within the time-out 3000
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.001" classname="OtherTest"/>
  <testcase name="testCase1" time="0.0" classname="OtherTest">
    <ignored/>
  </testcase> <!-- testCase1 -->
</testsuite>
