<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="lixiaoyan" name="OtherTest" tests="3" failures="0" timestamp="21 五月 2018 09:04:03 GMT" time="3.031" errors="1">
  <testcase name="testCase3" time="0.001" classname="OtherTest"/>
  <testcase name="testCase2" time="3.030" classname="OtherTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method OtherTest.testCase2() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method OtherTest.testCase2() didn't finish within the time-out 3000
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase1" classname="OtherTest">
    <skipped/>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- OtherTest -->
